name: berlin_nukus
description: Berlin-Nukus nemis tili o'quv markazi

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.5.0
  google_sign_in: ^6.2.2
  
  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  shimmer: ^3.0.0
  
  # State Management
  provider: ^6.1.1
  
  # Storage
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.2.1
  http: ^1.6.0
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  crypto: ^3.0.6
  flutter_tts: ^4.2.0
  speech_to_text: ^7.0.0
  permission_handler: ^11.3.1
  
  # Navigation
  go_router: ^13.0.0
  animated_theme_switcher: ^2.0.10
  mask_text_input_formatter: ^2.9.0
  audioplayers: ^6.6.0
  cached_network_image: ^3.4.1
  onesignal_flutter: ^5.5.5
  aws_signature_v4: ^0.6.10
  aws_common: ^0.7.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/logo.png"

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
    - assets/sounds/
    - assets/games/
    - env.txt