// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0dhqgCG5RQCG2jAjvQfJLKTvS63wmOqA',
    appId: '1:901891657911:web:7917fea136cc5ad577fd32',
    messagingSenderId: '901891657911',
    projectId: 'berlin-nukus-n1',
    authDomain: 'berlin-nukus-n1.firebaseapp.com',
    storageBucket: 'berlin-nukus-n1.firebasestorage.app',
    measurementId: 'G-W5Z60C7HZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUkNeshTUAMZGhs8If8YH0F93SW2ekjIY',
    appId: '1:901891657911:android:853b595e6540bd7377fd32',
    messagingSenderId: '901891657911',
    projectId: 'berlin-nukus-n1',
    storageBucket: 'berlin-nukus-n1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsb22GwcYhciYvT3MKEkm3NJSxTUY_XcA',
    appId: '1:901891657911:ios:304e0cb31c02905a77fd32',
    messagingSenderId: '901891657911',
    projectId: 'berlin-nukus-n1',
    storageBucket: 'berlin-nukus-n1.firebasestorage.app',
    iosClientId: '901891657911-611t5vcc45ojg3limu7f92npl6sk0knv.apps.googleusercontent.com',
    iosBundleId: 'com.example.berlinNukus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsb22GwcYhciYvT3MKEkm3NJSxTUY_XcA',
    appId: '1:901891657911:ios:304e0cb31c02905a77fd32',
    messagingSenderId: '901891657911',
    projectId: 'berlin-nukus-n1',
    storageBucket: 'berlin-nukus-n1.firebasestorage.app',
    iosClientId: '901891657911-611t5vcc45ojg3limu7f92npl6sk0knv.apps.googleusercontent.com',
    iosBundleId: 'com.example.berlinNukus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0dhqgCG5RQCG2jAjvQfJLKTvS63wmOqA',
    appId: '1:901891657911:web:78b4db5deaea541377fd32',
    messagingSenderId: '901891657911',
    projectId: 'berlin-nukus-n1',
    authDomain: 'berlin-nukus-n1.firebaseapp.com',
    storageBucket: 'berlin-nukus-n1.firebasestorage.app',
    measurementId: 'G-33G1P2FKKB',
  );

}