// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrASqHOvIbT_ZC5MkDqQzZxeGwwhpdSzc',
    appId: '1:31427206482:web:acdcf2484394c87dd5ee8b',
    messagingSenderId: '31427206482',
    projectId: 'berlin-nukus-nemis',
    authDomain: 'berlin-nukus-nemis.firebaseapp.com',
    storageBucket: 'berlin-nukus-nemis.firebasestorage.app',
    measurementId: 'G-0Z4E8WX58J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoXOw8qOMsmgkBJ8MXs-VigqtFANXHbRg',
    appId: '1:31427206482:android:ef5a38b9fe392557d5ee8b',
    messagingSenderId: '31427206482',
    projectId: 'berlin-nukus-nemis',
    storageBucket: 'berlin-nukus-nemis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgIN99PQ0BkZUw4JiFSdIkITcbl-CgAIU',
    appId: '1:31427206482:ios:c4af75592e47db51d5ee8b',
    messagingSenderId: '31427206482',
    projectId: 'berlin-nukus-nemis',
    storageBucket: 'berlin-nukus-nemis.firebasestorage.app',
    iosClientId: '31427206482-5b27rkqc5385k54r5clmlit55pidumet.apps.googleusercontent.com',
    iosBundleId: 'com.example.berlinNukus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgIN99PQ0BkZUw4JiFSdIkITcbl-CgAIU',
    appId: '1:31427206482:ios:c4af75592e47db51d5ee8b',
    messagingSenderId: '31427206482',
    projectId: 'berlin-nukus-nemis',
    storageBucket: 'berlin-nukus-nemis.firebasestorage.app',
    iosClientId: '31427206482-5b27rkqc5385k54r5clmlit55pidumet.apps.googleusercontent.com',
    iosBundleId: 'com.example.berlinNukus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrASqHOvIbT_ZC5MkDqQzZxeGwwhpdSzc',
    appId: '1:31427206482:web:aa35ad0b42e44888d5ee8b',
    messagingSenderId: '31427206482',
    projectId: 'berlin-nukus-nemis',
    authDomain: 'berlin-nukus-nemis.firebaseapp.com',
    storageBucket: 'berlin-nukus-nemis.firebasestorage.app',
    measurementId: 'G-L72TF0KCEP',
  );
}
