# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore
  exclude:
    - lib/services/audio_recorder_platform_web.dart
    - lib/services/tts_audio_web.dart
    - lib/utils/web_blob_url_web.dart

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
