import '../l10n/locale_manager.dart';
import 'game_words_i18n.dart';

class GameWords {
  // Der, Die, Das o'yini uchun 500+ so'z
  // A1 va A2 daraja, kategoriyalar bo'yicha
  static const List<Map<String, String>> derDieDasWords = [
    // ===== OILA VA INSONLAR (50 ta) =====
    {'word': 'der Mann', 'article': 'der', 'translation': 'Erkak'},
    {'word': 'die Frau', 'article': 'die', 'translation': 'Ayol'},
    {'word': 'das Kind', 'article': 'das', 'translation': 'Bola'},
    {'word': 'der Vater', 'article': 'der', 'translation': 'Ota'},
    {'word': 'die Mutter', 'article': 'die', 'translation': 'Ona'},
    {'word': 'der Bruder', 'article': 'der', 'translation': 'Aka/Uka'},
    {'word': 'die Schwester', 'article': 'die', 'translation': 'Opa/Singil'},
    {'word': 'der Sohn', 'article': 'der', 'translation': 'O\'g\'il'},
    {'word': 'die Tochter', 'article': 'die', 'translation': 'Qiz'},
    {'word': 'der Onkel', 'article': 'der', 'translation': 'Amaki/Tog\'a'},
    {'word': 'die Tante', 'article': 'die', 'translation': 'Xola/Amma'},
    {'word': 'der Opa', 'article': 'der', 'translation': 'Bobo'},
    {'word': 'die Oma', 'article': 'die', 'translation': 'Buvi'},
    {'word': 'der Freund', 'article': 'der', 'translation': 'Do\'st'},
    {'word': 'die Freundin', 'article': 'die', 'translation': 'Qiz do\'st'},
    {'word': 'der Nachbar', 'article': 'der', 'translation': 'Qo\'shni'},
    {'word': 'die Nachbarin', 'article': 'die', 'translation': 'Ayol qo\'shni'},
    {'word': 'das Baby', 'article': 'das', 'translation': 'Chaqaloq'},
    {'word': 'der Junge', 'article': 'der', 'translation': 'O\'g\'il bola'},
    {'word': 'das Mädchen', 'article': 'das', 'translation': 'Qiz bola'},
    {'word': 'der Chef', 'article': 'der', 'translation': 'Boshliq'},
    {'word': 'die Chefin', 'article': 'die', 'translation': 'Ayol boshliq'},
    {'word': 'der Kollege', 'article': 'der', 'translation': 'Hamkasb'},
    {'word': 'die Kollegin', 'article': 'die', 'translation': 'Ayol hamkasb'},
    {'word': 'der Arzt', 'article': 'der', 'translation': 'Shifokor'},
    {'word': 'die Ärztin', 'article': 'die', 'translation': 'Ayol shifokor'},
    {'word': 'der Lehrer', 'article': 'der', 'translation': 'O\'qituvchi'},
    {
      'word': 'die Lehrerin',
      'article': 'die',
      'translation': 'Ayol o\'qituvchi'
    },
    {'word': 'der Student', 'article': 'der', 'translation': 'Talaba'},
    {'word': 'die Studentin', 'article': 'die', 'translation': 'Ayol talaba'},
    {
      'word': 'der Polizist',
      'article': 'der',
      'translation': 'Politsiya xodimi'
    },
    {
      'word': 'die Polizistin',
      'article': 'die',
      'translation': 'Ayol politsiya'
    },
    {'word': 'der Verkäufer', 'article': 'der', 'translation': 'Sotuvchi'},
    {
      'word': 'die Verkäuferin',
      'article': 'die',
      'translation': 'Ayol sotuvchi'
    },
    {'word': 'der Kellner', 'article': 'der', 'translation': 'Ofitsiant'},
    {
      'word': 'die Kellnerin',
      'article': 'die',
      'translation': 'Ayol ofitsiant'
    },
    {'word': 'der Bäcker', 'article': 'der', 'translation': 'Novvoy'},
    {'word': 'der Kunde', 'article': 'der', 'translation': 'Xaridor'},
    {'word': 'die Kundin', 'article': 'die', 'translation': 'Ayol xaridor'},
    {'word': 'der Gast', 'article': 'der', 'translation': 'Mehmon'},
    {'word': 'die Gästin', 'article': 'die', 'translation': 'Ayol mehmon'},
    {'word': 'das Paar', 'article': 'das', 'translation': 'Juftlik'},
    {'word': 'der Cousin', 'article': 'der', 'translation': 'Amakivachcha'},
    {
      'word': 'die Cousine',
      'article': 'die',
      'translation': 'Amakivachcha qiz'
    },
    {'word': 'der Neffe', 'article': 'der', 'translation': 'Jiyan'},
    {'word': 'die Nichte', 'article': 'die', 'translation': 'Jiyan qiz'},
    {'word': 'der Enkel', 'article': 'der', 'translation': 'Nabira'},
    {'word': 'die Enkelin', 'article': 'die', 'translation': 'Nabira qiz'},
    {
      'word': 'das Geschwister',
      'article': 'das',
      'translation': 'Aka-uka/opa-singil'
    },
    {'word': 'die Eltern', 'article': 'die', 'translation': 'Ota-ona'},
    {'word': 'die Großeltern', 'article': 'die', 'translation': 'Bobo-buvi'},

    // ===== UY VA RO'ZG'OR (50 ta) =====
    {'word': 'das Haus', 'article': 'das', 'translation': 'Uy'},
    {'word': 'die Wohnung', 'article': 'die', 'translation': 'Kvartira'},
    {'word': 'das Zimmer', 'article': 'das', 'translation': 'Xona'},
    {'word': 'die Küche', 'article': 'die', 'translation': 'Oshxona'},
    {'word': 'das Bad', 'article': 'das', 'translation': 'Hammom'},
    {'word': 'das Schlafzimmer', 'article': 'das', 'translation': 'Yotoqxona'},
    {'word': 'das Wohnzimmer', 'article': 'das', 'translation': 'Mehmonxona'},
    {'word': 'der Tisch', 'article': 'der', 'translation': 'Stol'},
    {'word': 'der Stuhl', 'article': 'der', 'translation': 'Stul'},
    {'word': 'das Bett', 'article': 'das', 'translation': 'Krovat'},
    {'word': 'der Schrank', 'article': 'der', 'translation': 'Shkaf'},
    {'word': 'das Regal', 'article': 'das', 'translation': 'Javon'},
    {'word': 'die Lampe', 'article': 'die', 'translation': 'Lampa'},
    {'word': 'das Fenster', 'article': 'das', 'translation': 'Deraza'},
    {'word': 'die Tür', 'article': 'die', 'translation': 'Eshik'},
    {'word': 'der Teppich', 'article': 'der', 'translation': 'Gilam'},
    {'word': 'das Bild', 'article': 'das', 'translation': 'Rasm'},
    {'word': 'die Uhr', 'article': 'die', 'translation': 'Soat'},
    {'word': 'der Spiegel', 'article': 'der', 'translation': 'Ko\'zgu'},
    {'word': 'das Sofa', 'article': 'das', 'translation': 'Divan'},
    {'word': 'der Sessel', 'article': 'der', 'translation': 'Kreslo'},
    {'word': 'der Kühlschrank', 'article': 'der', 'translation': 'Muzlatgich'},
    {'word': 'der Herd', 'article': 'der', 'translation': 'Plita'},
    {'word': 'der Ofen', 'article': 'der', 'translation': 'Pechka'},
    {
      'word': 'die Waschmaschine',
      'article': 'die',
      'translation': 'Kir yuvish mashinasi'
    },
    {
      'word': 'der Staubsauger',
      'article': 'der',
      'translation': 'Changyutgich'
    },
    {'word': 'das Geschirr', 'article': 'das', 'translation': 'Idish-tovoq'},
    {'word': 'der Teller', 'article': 'der', 'translation': 'Tarelka'},
    {'word': 'die Tasse', 'article': 'die', 'translation': 'Piyola'},
    {'word': 'das Glas', 'article': 'das', 'translation': 'Stakan'},
    {'word': 'die Gabel', 'article': 'die', 'translation': 'Sanchqi'},
    {'word': 'das Messer', 'article': 'das', 'translation': 'Pichoq'},
    {'word': 'der Löffel', 'article': 'der', 'translation': 'Qoshiq'},
    {'word': 'der Topf', 'article': 'der', 'translation': 'Qozon'},
    {'word': 'die Pfanne', 'article': 'die', 'translation': 'Skovorodka'},
    {'word': 'der Schlüssel', 'article': 'der', 'translation': 'Kalit'},
    {'word': 'das Kissen', 'article': 'das', 'translation': 'Yostiq'},
    {'word': 'die Decke', 'article': 'die', 'translation': 'Ko\'rpa'},
    {'word': 'der Vorhang', 'article': 'der', 'translation': 'Parda'},
    {'word': 'der Wasserhahn', 'article': 'der', 'translation': 'Suv krani'},
    {'word': 'die Dusche', 'article': 'die', 'translation': 'Dush'},
    {'word': 'die Badewanne', 'article': 'die', 'translation': 'Vanna'},
    {'word': 'das Handtuch', 'article': 'das', 'translation': 'Sochiq'},
    {'word': 'die Seife', 'article': 'die', 'translation': 'Sovun'},
    {'word': 'der Mülleimer', 'article': 'der', 'translation': 'Axlat qutisi'},
    {'word': 'die Treppe', 'article': 'die', 'translation': 'Zina'},
    {'word': 'der Balkon', 'article': 'der', 'translation': 'Balkon'},
    {'word': 'der Keller', 'article': 'der', 'translation': 'Yerto\'la'},
    {'word': 'das Dach', 'article': 'das', 'translation': 'Tom'},
    {'word': 'der Garten', 'article': 'der', 'translation': 'Bog\''},

    // ===== OZIQ-OVQAT (50 ta) =====
    {'word': 'das Brot', 'article': 'das', 'translation': 'Non'},
    {'word': 'die Butter', 'article': 'die', 'translation': 'Sariyog\''},
    {'word': 'der Käse', 'article': 'der', 'translation': 'Pishloq'},
    {'word': 'die Milch', 'article': 'die', 'translation': 'Sut'},
    {'word': 'das Ei', 'article': 'das', 'translation': 'Tuxum'},
    {'word': 'der Joghurt', 'article': 'der', 'translation': 'Yogurt'},
    {'word': 'die Wurst', 'article': 'die', 'translation': 'Kolbasa'},
    {
      'word': 'der Schinken',
      'article': 'der',
      'translation': 'Go\'sht (sovuq)'
    },
    {'word': 'das Fleisch', 'article': 'das', 'translation': 'Go\'sht'},
    {'word': 'der Fisch', 'article': 'der', 'translation': 'Baliq'},
    {'word': 'das Hähnchen', 'article': 'das', 'translation': 'Tovuq go\'shti'},
    {'word': 'der Reis', 'article': 'der', 'translation': 'Guruch'},
    {'word': 'die Nudel', 'article': 'die', 'translation': 'Makaron'},
    {'word': 'die Kartoffel', 'article': 'die', 'translation': 'Kartoshka'},
    {'word': 'das Gemüse', 'article': 'das', 'translation': 'Sabzavot'},
    {'word': 'der Salat', 'article': 'der', 'translation': 'Salat'},
    {'word': 'die Tomate', 'article': 'die', 'translation': 'Pomidor'},
    {'word': 'die Gurke', 'article': 'die', 'translation': 'Bodring'},
    {'word': 'die Zwiebel', 'article': 'die', 'translation': 'Piyoz'},
    {'word': 'der Knoblauch', 'article': 'der', 'translation': 'Sarimsoq'},
    {'word': 'die Möhre', 'article': 'die', 'translation': 'Sabzi'},
    {'word': 'der Apfel', 'article': 'der', 'translation': 'Olma'},
    {'word': 'die Banane', 'article': 'die', 'translation': 'Banan'},
    {'word': 'die Orange', 'article': 'die', 'translation': 'Apelsin'},
    {'word': 'die Zitrone', 'article': 'die', 'translation': 'Limon'},
    {'word': 'die Erdbeere', 'article': 'die', 'translation': 'Qulupnay'},
    {'word': 'die Kirsche', 'article': 'die', 'translation': 'Olcha'},
    {'word': 'der Zucker', 'article': 'der', 'translation': 'Shakar'},
    {'word': 'das Salz', 'article': 'das', 'translation': 'Tuz'},
    {'word': 'der Pfeffer', 'article': 'der', 'translation': 'Qalampir'},
    {'word': 'das Öl', 'article': 'das', 'translation': 'Yog\''},
    {'word': 'der Essig', 'article': 'der', 'translation': 'Sirka'},
    {'word': 'die Suppe', 'article': 'die', 'translation': 'Sho\'rva'},
    {'word': 'die Soße', 'article': 'die', 'translation': 'Sous'},
    {'word': 'der Kuchen', 'article': 'der', 'translation': 'Pirog'},
    {'word': 'die Schokolade', 'article': 'die', 'translation': 'Shokolad'},
    {'word': 'das Eis', 'article': 'das', 'translation': 'Muzqaymoq'},
    {'word': 'der Kaffee', 'article': 'der', 'translation': 'Kofe'},
    {'word': 'der Tee', 'article': 'der', 'translation': 'Choy'},
    {'word': 'das Wasser', 'article': 'das', 'translation': 'Suv'},
    {'word': 'der Saft', 'article': 'der', 'translation': 'Sharbat'},
    {'word': 'das Bier', 'article': 'das', 'translation': 'Pivo'},
    {'word': 'der Wein', 'article': 'der', 'translation': 'Vino'},
    {'word': 'die Limonade', 'article': 'die', 'translation': 'Limonad'},
    {'word': 'das Brötchen', 'article': 'das', 'translation': 'Bulochka'},
    {'word': 'die Marmelade', 'article': 'die', 'translation': 'Murabbo'},
    {'word': 'der Honig', 'article': 'der', 'translation': 'Asal'},
    {'word': 'die Sahne', 'article': 'die', 'translation': 'Qaymoq'},
    {'word': 'der Quark', 'article': 'der', 'translation': 'Tvorog'},
    {'word': 'die Brezel', 'article': 'die', 'translation': 'Bretzel'},

    // ===== KIYIMLAR (35 ta) =====
    {'word': 'die Hose', 'article': 'die', 'translation': 'Shim'},
    {'word': 'das Hemd', 'article': 'das', 'translation': 'Ko\'ylak'},
    {'word': 'die Bluse', 'article': 'die', 'translation': 'Bluzka'},
    {'word': 'der Rock', 'article': 'der', 'translation': 'Yubka'},
    {
      'word': 'das Kleid',
      'article': 'das',
      'translation': 'Ko\'ylak (ayollar)'
    },
    {'word': 'der Anzug', 'article': 'der', 'translation': 'Kostyum'},
    {'word': 'die Jacke', 'article': 'die', 'translation': 'Kurtka'},
    {'word': 'der Mantel', 'article': 'der', 'translation': 'Palto'},
    {'word': 'der Pullover', 'article': 'der', 'translation': 'Sviter'},
    {'word': 'das T-Shirt', 'article': 'das', 'translation': 'Futbolka'},
    {'word': 'die Socke', 'article': 'die', 'translation': 'Paypoq'},
    {'word': 'der Schuh', 'article': 'der', 'translation': 'Oyoq kiyim'},
    {'word': 'der Stiefel', 'article': 'der', 'translation': 'Etik'},
    {'word': 'die Mütze', 'article': 'die', 'translation': 'Shapka'},
    {'word': 'der Hut', 'article': 'der', 'translation': 'Shlyapa'},
    {'word': 'der Schal', 'article': 'der', 'translation': 'Sharf'},
    {'word': 'der Handschuh', 'article': 'der', 'translation': 'Qo\'lqop'},
    {'word': 'die Unterwäsche', 'article': 'die', 'translation': 'Ichki kiyim'},
    {'word': 'der Gürtel', 'article': 'der', 'translation': 'Kamar'},
    {'word': 'die Krawatte', 'article': 'die', 'translation': 'Galstuk'},
    {'word': 'der Knopf', 'article': 'der', 'translation': 'Tugma'},
    {'word': 'der Reißverschluss', 'article': 'der', 'translation': 'Molniya'},
    {'word': 'die Tasche', 'article': 'die', 'translation': 'Sumka'},
    {'word': 'der Rucksack', 'article': 'der', 'translation': 'Ryukzak'},
    {'word': 'die Brille', 'article': 'die', 'translation': 'Ko\'zoynak'},
    {'word': 'die Armbanduhr', 'article': 'die', 'translation': 'Qo\'l soati'},
    {'word': 'der Ring', 'article': 'der', 'translation': 'Uzuk'},
    {'word': 'die Kette', 'article': 'die', 'translation': 'Zanjir'},
    {'word': 'der Ohrring', 'article': 'der', 'translation': 'Sirg\'a'},
    {'word': 'die Sandale', 'article': 'die', 'translation': 'Sandal'},
    {
      'word': 'der Badeanzug',
      'article': 'der',
      'translation': 'Cho\'milish kiyimi'
    },
    {'word': 'die Jeans', 'article': 'die', 'translation': 'Jinsi shim'},
    {
      'word': 'der Trainingsanzug',
      'article': 'der',
      'translation': 'Sport kostyumi'
    },
    {'word': 'das Sweatshirt', 'article': 'das', 'translation': 'Svitshot'},
    {'word': 'die Shorts', 'article': 'die', 'translation': 'Kalta shim'},

    // ===== HAYVONLAR (40 ta) =====
    {'word': 'der Hund', 'article': 'der', 'translation': 'It'},
    {'word': 'die Katze', 'article': 'die', 'translation': 'Mushuk'},
    {'word': 'das Pferd', 'article': 'das', 'translation': 'Ot'},
    {'word': 'die Kuh', 'article': 'die', 'translation': 'Sigir'},
    {'word': 'das Schwein', 'article': 'das', 'translation': 'Cho\'chqa'},
    {'word': 'das Schaf', 'article': 'das', 'translation': 'Qo\'y'},
    {'word': 'die Ziege', 'article': 'die', 'translation': 'Echki'},
    {'word': 'das Huhn', 'article': 'das', 'translation': 'Tovuq'},
    {'word': 'der Hahn', 'article': 'der', 'translation': 'Xo\'roz'},
    {'word': 'die Ente', 'article': 'die', 'translation': 'O\'rdak'},
    {'word': 'die Gans', 'article': 'die', 'translation': 'G\'oz'},
    {'word': 'der Vogel', 'article': 'der', 'translation': 'Qush'},
    {'word': 'der Adler', 'article': 'der', 'translation': 'Burgut'},
    {'word': 'die Eule', 'article': 'die', 'translation': 'Boyqush'},
    {'word': 'der Fisch', 'article': 'der', 'translation': 'Baliq'},
    {'word': 'der Hai', 'article': 'der', 'translation': 'Akula'},
    {'word': 'der Wal', 'article': 'der', 'translation': 'Kit'},
    {'word': 'der Delfin', 'article': 'der', 'translation': 'Delfin'},
    {'word': 'der Bär', 'article': 'der', 'translation': 'Ayiq'},
    {'word': 'der Wolf', 'article': 'der', 'translation': 'Bo\'ri'},
    {'word': 'der Fuchs', 'article': 'der', 'translation': 'Tulki'},
    {'word': 'der Hase', 'article': 'der', 'translation': 'Quyon'},
    {'word': 'das Kaninchen', 'article': 'das', 'translation': 'Uy quyoni'},
    {'word': 'das Eichhörnchen', 'article': 'das', 'translation': 'Olmaxon'},
    {'word': 'die Maus', 'article': 'die', 'translation': 'Sichqon'},
    {'word': 'die Ratte', 'article': 'die', 'translation': 'Kalamush'},
    {'word': 'der Igel', 'article': 'der', 'translation': 'Tipratikan'},
    {'word': 'die Schlange', 'article': 'die', 'translation': 'Ilon'},
    {'word': 'die Schildkröte', 'article': 'die', 'translation': 'Toshbaqa'},
    {'word': 'der Frosch', 'article': 'der', 'translation': 'Baqa'},
    {'word': 'der Affe', 'article': 'der', 'translation': 'Maymun'},
    {'word': 'der Elefant', 'article': 'der', 'translation': 'Fil'},
    {'word': 'der Löwe', 'article': 'der', 'translation': 'Arslon'},
    {'word': 'der Tiger', 'article': 'der', 'translation': 'Yo\'lbars'},
    {'word': 'die Giraffe', 'article': 'die', 'translation': 'Jirafa'},
    {'word': 'das Zebra', 'article': 'das', 'translation': 'Zebra'},
    {'word': 'das Krokodil', 'article': 'das', 'translation': 'Timsoh'},
    {'word': 'der Pinguin', 'article': 'der', 'translation': 'Pingvin'},
    {'word': 'der Schmetterling', 'article': 'der', 'translation': 'Kapalak'},
    {'word': 'die Biene', 'article': 'die', 'translation': 'Asalari'},

    // ===== MAKTAB VA OFIS (35 ta) =====
    {'word': 'die Schule', 'article': 'die', 'translation': 'Maktab'},
    {'word': 'die Universität', 'article': 'die', 'translation': 'Universitet'},
    {
      'word': 'das Klassenzimmer',
      'article': 'das',
      'translation': 'Sinf xonasi'
    },
    {'word': 'der Lehrer', 'article': 'der', 'translation': 'O\'qituvchi'},
    {'word': 'der Schüler', 'article': 'der', 'translation': 'O\'quvchi'},
    {'word': 'das Buch', 'article': 'das', 'translation': 'Kitob'},
    {'word': 'das Heft', 'article': 'das', 'translation': 'Daftar'},
    {'word': 'der Kugelschreiber', 'article': 'der', 'translation': 'Ruchka'},
    {'word': 'der Bleistift', 'article': 'der', 'translation': 'Qalam'},
    {'word': 'der Radiergummi', 'article': 'der', 'translation': 'O\'chirgich'},
    {'word': 'das Lineal', 'article': 'das', 'translation': 'Lineyka'},
    {'word': 'die Schere', 'article': 'die', 'translation': 'Qaychi'},
    {'word': 'der Kleber', 'article': 'der', 'translation': 'Yelim'},
    {'word': 'die Tafel', 'article': 'die', 'translation': 'Doska'},
    {
      'word': 'der Taschenrechner',
      'article': 'der',
      'translation': 'Kalkulyator'
    },
    {'word': 'das Wörterbuch', 'article': 'das', 'translation': 'Lug\'at'},
    {'word': 'der Ordner', 'article': 'der', 'translation': 'Papka'},
    {'word': 'der Computer', 'article': 'der', 'translation': 'Kompyuter'},
    {'word': 'der Drucker', 'article': 'der', 'translation': 'Printer'},
    {'word': 'das Handy', 'article': 'das', 'translation': 'Telefon'},
    {'word': 'die Tastatur', 'article': 'die', 'translation': 'Klaviatura'},
    {'word': 'die Maus', 'article': 'die', 'translation': 'Sichqoncha'},
    {'word': 'der Bildschirm', 'article': 'der', 'translation': 'Monitor'},
    {'word': 'der Tisch', 'article': 'der', 'translation': 'Stol'},
    {'word': 'der Stuhl', 'article': 'der', 'translation': 'Stul'},
    {'word': 'das Papier', 'article': 'das', 'translation': 'Qog\'oz'},
    {'word': 'der Umschlag', 'article': 'der', 'translation': 'Konvert'},
    {'word': 'die Briefmarke', 'article': 'die', 'translation': 'Marka'},
    {'word': 'der Kalender', 'article': 'der', 'translation': 'Kalendar'},
    {'word': 'die Notiz', 'article': 'die', 'translation': 'Eslatma'},
    {'word': 'der Rucksack', 'article': 'der', 'translation': 'Ryukzak'},
    {'word': 'die Pause', 'article': 'die', 'translation': 'Tanaffus'},
    {'word': 'die Prüfung', 'article': 'die', 'translation': 'Imtihon'},
    {'word': 'die Hausaufgabe', 'article': 'die', 'translation': 'Uy vazifasi'},
    {'word': 'das Zeugnis', 'article': 'das', 'translation': 'Baholar tabeli'},

    // ===== TABIAT VA OB-HAVO (40 ta) =====
    {'word': 'die Sonne', 'article': 'die', 'translation': 'Quyosh'},
    {'word': 'der Mond', 'article': 'der', 'translation': 'Oy'},
    {'word': 'der Stern', 'article': 'der', 'translation': 'Yulduz'},
    {'word': 'der Himmel', 'article': 'der', 'translation': 'Osmon'},
    {'word': 'die Wolke', 'article': 'die', 'translation': 'Bulut'},
    {'word': 'der Regen', 'article': 'der', 'translation': 'Yomg\'ir'},
    {'word': 'der Schnee', 'article': 'der', 'translation': 'Qor'},
    {'word': 'der Wind', 'article': 'der', 'translation': 'Shamol'},
    {'word': 'der Sturm', 'article': 'der', 'translation': 'Bo\'ron'},
    {'word': 'der Blitz', 'article': 'der', 'translation': 'Chaqmoq'},
    {'word': 'der Donner', 'article': 'der', 'translation': 'Momaqaldiroq'},
    {'word': 'der Regenbogen', 'article': 'der', 'translation': 'Kamalak'},
    {'word': 'der Nebel', 'article': 'der', 'translation': 'Tuman'},
    {'word': 'das Eis', 'article': 'das', 'translation': 'Muz'},
    {'word': 'die Hitze', 'article': 'die', 'translation': 'Issiq'},
    {'word': 'die Kälte', 'article': 'die', 'translation': 'Sovuq'},
    {'word': 'der Baum', 'article': 'der', 'translation': 'Daraxt'},
    {'word': 'die Blume', 'article': 'die', 'translation': 'Gul'},
    {'word': 'die Rose', 'article': 'die', 'translation': 'Atirgul'},
    {'word': 'das Gras', 'article': 'das', 'translation': 'O\'t'},
    {'word': 'der Wald', 'article': 'der', 'translation': 'O\'rmon'},
    {'word': 'der Berg', 'article': 'der', 'translation': 'Tog\''},
    {'word': 'das Tal', 'article': 'das', 'translation': 'Vodiy'},
    {'word': 'der Fluss', 'article': 'der', 'translation': 'Daryo'},
    {'word': 'der See', 'article': 'der', 'translation': 'Ko\'l'},
    {'word': 'das Meer', 'article': 'das', 'translation': 'Dengiz'},
    {'word': 'der Strand', 'article': 'der', 'translation': 'Plyaj'},
    {'word': 'die Insel', 'article': 'die', 'translation': 'Orol'},
    {'word': 'der Stein', 'article': 'der', 'translation': 'Tosh'},
    {'word': 'der Sand', 'article': 'der', 'translation': 'Qum'},
    {'word': 'die Erde', 'article': 'die', 'translation': 'Yer'},
    {'word': 'die Luft', 'article': 'die', 'translation': 'Havo'},
    {'word': 'das Feuer', 'article': 'das', 'translation': 'Olov'},
    {'word': 'der Rauch', 'article': 'der', 'translation': 'Tutun'},
    {'word': 'die Welle', 'article': 'die', 'translation': 'To\'lqin'},
    {'word': 'die Brücke', 'article': 'die', 'translation': 'Ko\'prik'},
    {'word': 'der Weg', 'article': 'der', 'translation': 'Yo\'l'},
    {'word': 'die Natur', 'article': 'die', 'translation': 'Tabiat'},
    {
      'word': 'der Sonnenschein',
      'article': 'der',
      'translation': 'Quyosh nuri'
    },
    {'word': 'der Schatten', 'article': 'der', 'translation': 'Soya'},

    // ===== TRANSPORT (30 ta) =====
    {'word': 'das Auto', 'article': 'das', 'translation': 'Mashina'},
    {'word': 'der Bus', 'article': 'der', 'translation': 'Avtobus'},
    {'word': 'der Zug', 'article': 'der', 'translation': 'Poyezd'},
    {'word': 'die U-Bahn', 'article': 'die', 'translation': 'Metro'},
    {'word': 'die Straßenbahn', 'article': 'die', 'translation': 'Tramvay'},
    {'word': 'das Fahrrad', 'article': 'das', 'translation': 'Velosiped'},
    {'word': 'das Motorrad', 'article': 'das', 'translation': 'Mototsikl'},
    {'word': 'das Flugzeug', 'article': 'das', 'translation': 'Samolyot'},
    {'word': 'das Schiff', 'article': 'das', 'translation': 'Kema'},
    {'word': 'das Taxi', 'article': 'das', 'translation': 'Taksi'},
    {'word': 'die Haltestelle', 'article': 'die', 'translation': 'Bekat'},
    {'word': 'der Bahnhof', 'article': 'der', 'translation': 'Vokzal'},
    {'word': 'der Flughafen', 'article': 'der', 'translation': 'Aeroport'},
    {'word': 'die Fahrkarte', 'article': 'die', 'translation': 'Bilet'},
    {'word': 'der Fahrplan', 'article': 'der', 'translation': 'Jadval'},
    {'word': 'die Ampel', 'article': 'die', 'translation': 'Svetofor'},
    {
      'word': 'der Führerschein',
      'article': 'der',
      'translation': 'Haydovchilik guvohnomasi'
    },
    {'word': 'der Stau', 'article': 'der', 'translation': 'Tirbandlik'},
    {'word': 'die Straße', 'article': 'die', 'translation': 'Ko\'cha'},
    {'word': 'der Gehweg', 'article': 'der', 'translation': 'Yo\'lak'},
    {'word': 'die Kreuzung', 'article': 'die', 'translation': 'Chorraha'},
    {'word': 'die Autobahn', 'article': 'die', 'translation': 'Avtoban'},
    {'word': 'der Reifen', 'article': 'der', 'translation': 'Shina'},
    {'word': 'das Benzin', 'article': 'das', 'translation': 'Benzin'},
    {'word': 'der Motor', 'article': 'der', 'translation': 'Motor'},
    {'word': 'der Unfall', 'article': 'der', 'translation': 'Avariya'},
    {'word': 'die Panne', 'article': 'die', 'translation': 'Buzilish'},
    {'word': 'der Lkw', 'article': 'der', 'translation': 'Yuk mashinasi'},
    {'word': 'der Hubschrauber', 'article': 'der', 'translation': 'Vertolyot'},
    {'word': 'die Fähre', 'article': 'die', 'translation': 'Parom'},

    // ===== SHAHAR VA BINOLAR (35 ta) =====
    {'word': 'die Stadt', 'article': 'die', 'translation': 'Shahar'},
    {'word': 'das Dorf', 'article': 'das', 'translation': 'Qishloq'},
    {'word': 'das Gebäude', 'article': 'das', 'translation': 'Bino'},
    {'word': 'der Supermarkt', 'article': 'der', 'translation': 'Supermarket'},
    {'word': 'die Bäckerei', 'article': 'die', 'translation': 'Novvoyxona'},
    {'word': 'die Apotheke', 'article': 'die', 'translation': 'Dorixona'},
    {'word': 'das Krankenhaus', 'article': 'das', 'translation': 'Kasalxona'},
    {'word': 'die Polizei', 'article': 'die', 'translation': 'Politsiya'},
    {
      'word': 'die Feuerwehr',
      'article': 'die',
      'translation': 'O\'t o\'chirish'
    },
    {'word': 'das Rathaus', 'article': 'das', 'translation': 'Munitsipalitet'},
    {'word': 'die Post', 'article': 'die', 'translation': 'Pochta'},
    {'word': 'die Bank', 'article': 'die', 'translation': 'Bank'},
    {'word': 'das Hotel', 'article': 'das', 'translation': 'Mehmonxona'},
    {'word': 'das Restaurant', 'article': 'das', 'translation': 'Restoran'},
    {'word': 'das Café', 'article': 'das', 'translation': 'Kafe'},
    {'word': 'das Kino', 'article': 'das', 'translation': 'Kinoteatr'},
    {'word': 'das Museum', 'article': 'das', 'translation': 'Muzey'},
    {'word': 'das Theater', 'article': 'das', 'translation': 'Teatr'},
    {'word': 'die Bibliothek', 'article': 'die', 'translation': 'Kutubxona'},
    {'word': 'der Park', 'article': 'der', 'translation': 'Park'},
    {
      'word': 'der Spielplatz',
      'article': 'der',
      'translation': 'O\'yin maydonchasi'
    },
    {'word': 'die Kirche', 'article': 'die', 'translation': 'Cherkov'},
    {'word': 'die Moschee', 'article': 'die', 'translation': 'Masjid'},
    {'word': 'der Markt', 'article': 'der', 'translation': 'Bozor'},
    {'word': 'das Schwimmbad', 'article': 'das', 'translation': 'Basseyn'},
    {'word': 'das Stadion', 'article': 'das', 'translation': 'Stadion'},
    {'word': 'der Zoo', 'article': 'der', 'translation': 'Hayvonot bog\'i'},
    {'word': 'die Garage', 'article': 'die', 'translation': 'Garaj'},
    {'word': 'der Parkplatz', 'article': 'der', 'translation': 'Avtoturargoh'},
    {'word': 'die Ampel', 'article': 'die', 'translation': 'Svetofor'},
    {
      'word': 'der Zebrastreifen',
      'article': 'der',
      'translation': 'Piyodalar o\'tish joyi'
    },
    {'word': 'das Kino', 'article': 'das', 'translation': 'Kinoteatr'},
    {'word': 'die Disco', 'article': 'die', 'translation': 'Diskoteka'},
    {'word': 'der Friseur', 'article': 'der', 'translation': 'Sartarosh'},
    {
      'word': 'die Reinigung',
      'article': 'die',
      'translation': 'Kimyoviy tozalash'
    },

    // ===== SPORT VA SOG'LIQ (30 ta) =====
    {'word': 'der Sport', 'article': 'der', 'translation': 'Sport'},
    {'word': 'der Fußball', 'article': 'der', 'translation': 'Futbol'},
    {'word': 'der Basketball', 'article': 'der', 'translation': 'Basketbol'},
    {'word': 'das Tennis', 'article': 'das', 'translation': 'Tennis'},
    {'word': 'das Schwimmen', 'article': 'das', 'translation': 'Suzish'},
    {'word': 'der Ball', 'article': 'der', 'translation': 'Koptok'},
    {'word': 'das Tor', 'article': 'das', 'translation': 'Darvoza'},
    {'word': 'der Spieler', 'article': 'der', 'translation': 'O\'yinchi'},
    {'word': 'die Mannschaft', 'article': 'die', 'translation': 'Jamoa'},
    {'word': 'der Sieg', 'article': 'der', 'translation': 'G\'alaba'},
    {'word': 'die Niederlage', 'article': 'die', 'translation': 'Mag\'lubiyat'},
    {'word': 'die Gesundheit', 'article': 'die', 'translation': 'Salomatlik'},
    {'word': 'der Körper', 'article': 'der', 'translation': 'Tana'},
    {'word': 'der Kopf', 'article': 'der', 'translation': 'Bosh'},
    {'word': 'das Auge', 'article': 'das', 'translation': 'Ko\'z'},
    {'word': 'das Ohr', 'article': 'das', 'translation': 'Quloq'},
    {'word': 'die Nase', 'article': 'die', 'translation': 'Burun'},
    {'word': 'der Mund', 'article': 'der', 'translation': 'Og\'iz'},
    {'word': 'der Zahn', 'article': 'der', 'translation': 'Tish'},
    {'word': 'die Hand', 'article': 'die', 'translation': 'Qo\'l'},
    {'word': 'der Finger', 'article': 'der', 'translation': 'Barmoq'},
    {'word': 'der Fuß', 'article': 'der', 'translation': 'Oyoq'},
    {'word': 'das Bein', 'article': 'das', 'translation': 'Oyoq'},
    {'word': 'der Rücken', 'article': 'der', 'translation': 'Orqa'},
    {'word': 'der Bauch', 'article': 'der', 'translation': 'Qorin'},
    {'word': 'das Herz', 'article': 'das', 'translation': 'Yurak'},
    {'word': 'die Medizin', 'article': 'die', 'translation': 'Dori'},
    {'word': 'die Tablette', 'article': 'die', 'translation': 'Tabletka'},
    {'word': 'der Schmerz', 'article': 'der', 'translation': 'Og\'riq'},
    {'word': 'die Grippe', 'article': 'die', 'translation': 'Gripp'},

    // ===== VAQT VA MAVSUMLAR (25 ta) =====
    {'word': 'der Tag', 'article': 'der', 'translation': 'Kun'},
    {'word': 'die Nacht', 'article': 'die', 'translation': 'Tun'},
    {'word': 'der Morgen', 'article': 'der', 'translation': 'Ertalab'},
    {'word': 'der Abend', 'article': 'der', 'translation': 'Kechqurun'},
    {'word': 'die Woche', 'article': 'die', 'translation': 'Hafta'},
    {'word': 'der Monat', 'article': 'der', 'translation': 'Oy'},
    {'word': 'das Jahr', 'article': 'das', 'translation': 'Yil'},
    {'word': 'die Stunde', 'article': 'die', 'translation': 'Soat'},
    {'word': 'die Minute', 'article': 'die', 'translation': 'Daqiqa'},
    {'word': 'die Sekunde', 'article': 'die', 'translation': 'Soniya'},
    {'word': 'der Montag', 'article': 'der', 'translation': 'Dushanba'},
    {'word': 'der Dienstag', 'article': 'der', 'translation': 'Seshanba'},
    {'word': 'der Mittwoch', 'article': 'der', 'translation': 'Chorshanba'},
    {'word': 'der Donnerstag', 'article': 'der', 'translation': 'Payshanba'},
    {'word': 'der Freitag', 'article': 'der', 'translation': 'Juma'},
    {'word': 'der Samstag', 'article': 'der', 'translation': 'Shanba'},
    {'word': 'der Sonntag', 'article': 'der', 'translation': 'Yakshanba'},
    {'word': 'der Frühling', 'article': 'der', 'translation': 'Bahor'},
    {'word': 'der Sommer', 'article': 'der', 'translation': 'Yoz'},
    {'word': 'der Herbst', 'article': 'der', 'translation': 'Kuz'},
    {'word': 'der Winter', 'article': 'der', 'translation': 'Qish'},
    {'word': 'der Januar', 'article': 'der', 'translation': 'Yanvar'},
    {'word': 'der Februar', 'article': 'der', 'translation': 'Fevral'},
    {'word': 'der März', 'article': 'der', 'translation': 'Mart'},
    {'word': 'der April', 'article': 'der', 'translation': 'Aprel'},
    {'word': 'der Mai', 'article': 'der', 'translation': 'May'},
    {'word': 'der Juni', 'article': 'der', 'translation': 'Iyun'},
    {'word': 'der Juli', 'article': 'der', 'translation': 'Iyul'},
    {'word': 'der August', 'article': 'der', 'translation': 'Avgust'},
    {'word': 'der September', 'article': 'der', 'translation': 'Sentabr'},
    {'word': 'der Oktober', 'article': 'der', 'translation': 'Oktabr'},
    {'word': 'der November', 'article': 'der', 'translation': 'Noyabr'},
    {'word': 'der Dezember', 'article': 'der', 'translation': 'Dekabr'},
    {
      'word': 'das Wochenende',
      'article': 'das',
      'translation': 'Dam olish kuni'
    },
    {'word': 'der Feiertag', 'article': 'der', 'translation': 'Bayram'},

    // ===== BOSHQA MUHIM SO'ZLAR (40 ta) =====
    {'word': 'das Geld', 'article': 'das', 'translation': 'Pul'},
    {'word': 'der Preis', 'article': 'der', 'translation': 'Narx'},
    {'word': 'das Geschenk', 'article': 'das', 'translation': 'Sovg\'a'},
    {'word': 'die Farbe', 'article': 'die', 'translation': 'Rang'},
    {'word': 'der Name', 'article': 'der', 'translation': 'Ism'},
    {'word': 'die Adresse', 'article': 'die', 'translation': 'Manzil'},
    {'word': 'die Nummer', 'article': 'die', 'translation': 'Raqam'},
    {'word': 'die Frage', 'article': 'die', 'translation': 'Savol'},
    {'word': 'die Antwort', 'article': 'die', 'translation': 'Javob'},
    {'word': 'die Idee', 'article': 'die', 'translation': 'Fikr'},
    {'word': 'das Problem', 'article': 'das', 'translation': 'Muammo'},
    {'word': 'die Lösung', 'article': 'die', 'translation': 'Yechim'},
    {'word': 'der Fehler', 'article': 'der', 'translation': 'Xato'},
    {'word': 'der Unterschied', 'article': 'der', 'translation': 'Farq'},
    {'word': 'die Meinung', 'article': 'die', 'translation': 'Fikr'},
    {'word': 'die Nachricht', 'article': 'die', 'translation': 'Xabar'},
    {'word': 'der Brief', 'article': 'der', 'translation': 'Xat'},
    {'word': 'das Paket', 'article': 'das', 'translation': 'Posilka'},
    {'word': 'die Zeitung', 'article': 'die', 'translation': 'Gazeta'},
    {'word': 'die Zeitschrift', 'article': 'die', 'translation': 'Jurnal'},
    {'word': 'die Sprache', 'article': 'die', 'translation': 'Til'},
    {'word': 'die Musik', 'article': 'die', 'translation': 'Musiqa'},
    {'word': 'das Lied', 'article': 'das', 'translation': 'Qo\'shiq'},
    {'word': 'der Film', 'article': 'der', 'translation': 'Film'},
    {'word': 'das Spiel', 'article': 'das', 'translation': 'O\'yin'},
    {'word': 'die Reise', 'article': 'die', 'translation': 'Sayohat'},
    {'word': 'der Urlaub', 'article': 'der', 'translation': 'Ta\'til'},
    {'word': 'die Arbeit', 'article': 'die', 'translation': 'Ish'},
    {'word': 'der Beruf', 'article': 'der', 'translation': 'Kasb'},
    {'word': 'die Firma', 'article': 'die', 'translation': 'Firma'},
    {'word': 'das Büro', 'article': 'das', 'translation': 'Ofis'},
    {'word': 'der Termin', 'article': 'der', 'translation': 'Uchrashuv'},
    {'word': 'die Besprechung', 'article': 'die', 'translation': 'Yig\'ilish'},
    {'word': 'der Vertrag', 'article': 'der', 'translation': 'Shartnoma'},
    {'word': 'die Rechnung', 'article': 'die', 'translation': 'Hisob'},
    {'word': 'der Ausweis', 'article': 'der', 'translation': 'Guvohnoma'},
    {'word': 'der Pass', 'article': 'der', 'translation': 'Pasport'},
    {'word': 'das Visum', 'article': 'das', 'translation': 'Viza'},
    {'word': 'die Grenze', 'article': 'die', 'translation': 'Chegara'},
    {'word': 'die Sitte', 'article': 'die', 'translation': 'Urf-odat'},
    {'word': 'die Kunst', 'article': 'die', 'translation': 'San\'at'},
    {'word': 'der Krieg', 'article': 'der', 'translation': 'Urush'},
    {'word': 'der Frieden', 'article': 'der', 'translation': 'Tinchlik'},
    {'word': 'die Welt', 'article': 'die', 'translation': 'Dunyo'},
    {'word': 'der Traum', 'article': 'der', 'translation': 'Tush/Orzu'},
    {'word': 'das Glück', 'article': 'das', 'translation': 'Omad/Baxt'},
    {'word': 'die Angst', 'article': 'die', 'translation': 'Qo\'rquv'},
    {'word': 'die Hoffnung', 'article': 'die', 'translation': 'Umid'},
    {'word': 'die Liebe', 'article': 'die', 'translation': 'Sevgi'},
    {'word': 'der Hass', 'article': 'der', 'translation': 'Nafrat'},

    // ===== KASBLAR VA ISH (30 ta) =====
    {'word': 'der Ingenieur', 'article': 'der', 'translation': 'Muhandis'},
    {
      'word': 'die Ingenieurin',
      'article': 'die',
      'translation': 'Ayol muhandis'
    },
    {'word': 'der Architekt', 'article': 'der', 'translation': 'Arxitektor'},
    {
      'word': 'die Architektin',
      'article': 'die',
      'translation': 'Ayol arxitektor'
    },
    {'word': 'der Schauspieler', 'article': 'der', 'translation': 'Aktyor'},
    {'word': 'die Schauspielerin', 'article': 'die', 'translation': 'Aktrisa'},
    {
      'word': 'der Sänger',
      'article': 'der',
      'translation': 'Qo\'shiqchi (erkak)'
    },
    {
      'word': 'die Sängerin',
      'article': 'die',
      'translation': 'Qo\'shiqchi (ayol)'
    },
    {'word': 'der Autor', 'article': 'der', 'translation': 'Yozuvchi'},
    {'word': 'die Autorin', 'article': 'die', 'translation': 'Ayol yozuvchi'},
    {'word': 'der Journalist', 'article': 'der', 'translation': 'Jurnalist'},
    {
      'word': 'die Journalistin',
      'article': 'die',
      'translation': 'Ayol jurnalist'
    },
    {'word': 'der Fotograf', 'article': 'der', 'translation': 'Fotograf'},
    {
      'word': 'die Fotografin',
      'article': 'die',
      'translation': 'Ayol fotograf'
    },
    {'word': 'der Mechaniker', 'article': 'der', 'translation': 'Mexanik'},
    {'word': 'der Elektriker', 'article': 'der', 'translation': 'Elektrik'},
    {'word': 'der Bauer', 'article': 'der', 'translation': 'Fermer'},
    {'word': 'die Bäuerin', 'article': 'die', 'translation': 'Ayol fermer'},
    {'word': 'der Friseur', 'article': 'der', 'translation': 'Sartarosh'},
    {
      'word': 'die Friseurin',
      'article': 'die',
      'translation': 'Ayol sartarosh'
    },
    {'word': 'der Pilot', 'article': 'der', 'translation': 'Uchuvchi'},
    {'word': 'die Pilotin', 'article': 'die', 'translation': 'Ayol uchuvchi'},
    {'word': 'der Anwalt', 'article': 'der', 'translation': 'Advokat'},
    {'word': 'die Anwältin', 'article': 'die', 'translation': 'Ayol advokat'},
    {'word': 'der Richter', 'article': 'der', 'translation': 'Sudya'},
    {'word': 'die Richterin', 'article': 'die', 'translation': 'Ayol sudya'},
    {'word': 'der Zahnarzt', 'article': 'der', 'translation': 'Tish shifokori'},
    {
      'word': 'die Zahnärztin',
      'article': 'die',
      'translation': 'Ayol tish shifokori'
    },
    {'word': 'der Politiker', 'article': 'der', 'translation': 'Siyosatchi'},
    {
      'word': 'die Politikerin',
      'article': 'die',
      'translation': 'Ayol siyosatchi'
    },

    // ===== TANA VA SOG'LIQ (QO'SHIMCHA) (20 ta) =====
    {'word': 'der Hals', 'article': 'der', 'translation': 'Bo\'yin'},
    {'word': 'die Schulter', 'article': 'die', 'translation': 'Yelka'},
    {'word': 'der Arm', 'article': 'der', 'translation': 'Qo\'l (bilak)'},
    {'word': 'das Knie', 'article': 'das', 'translation': 'Tizza'},
    {'word': 'der Zeh', 'article': 'der', 'translation': 'Oyoq barmog\'i'},
    {'word': 'die Haut', 'article': 'die', 'translation': 'Teri'},
    {'word': 'das Blut', 'article': 'das', 'translation': 'Qon'},
    {'word': 'das Gehirn', 'article': 'das', 'translation': 'Miya'},
    {'word': 'der Muskel', 'article': 'der', 'translation': 'Mushak'},
    {'word': 'der Knochen', 'article': 'der', 'translation': 'Suyak'},
    {
      'word': 'die Zunge',
      'article': 'die',
      'translation': 'Til (tana a\'zosi)'
    },
    {'word': 'die Lippe', 'article': 'die', 'translation': 'Lab'},
    {'word': 'das Haar', 'article': 'das', 'translation': 'Soch'},
    {'word': 'das Gesicht', 'article': 'das', 'translation': 'Yuz'},
    {'word': 'der Magen', 'article': 'der', 'translation': 'Oshqozon'},
    {'word': 'die Lunge', 'article': 'die', 'translation': 'O\'pka'},
    {'word': 'die Krankheit', 'article': 'die', 'translation': 'Kasallik'},
    {'word': 'das Fieber', 'article': 'das', 'translation': 'Isitma'},
    {'word': 'der Husten', 'article': 'der', 'translation': 'Yo\'tal'},
    {'word': 'die Apotheke', 'article': 'die', 'translation': 'Dorixona'},

    // ===== ASBOB VA USKUNALAR (30 ta) =====
    {'word': 'der Hammer', 'article': 'der', 'translation': 'Bolg\'a'},
    {'word': 'der Nagel', 'article': 'der', 'translation': 'Mix'},
    {'word': 'die Schraube', 'article': 'die', 'translation': 'Buruq (Vint)'},
    {
      'word': 'der Schraubenzieher',
      'article': 'der',
      'translation': 'Otvyortka'
    },
    {'word': 'die Zange', 'article': 'die', 'translation': 'Ombir'},
    {'word': 'die Säge', 'article': 'die', 'translation': 'Arra'},
    {'word': 'der Bohrer', 'article': 'der', 'translation': 'Drel'},
    {'word': 'das Werkzeug', 'article': 'das', 'translation': 'Asbob'},
    {'word': 'der Pinsel', 'article': 'der', 'translation': 'Mo\'yqalam'},
    {'word': 'die Schaufel', 'article': 'die', 'translation': 'Kurak'},
    {'word': 'der Eimer', 'article': 'der', 'translation': 'Paqir'},
    {'word': 'der Besen', 'article': 'der', 'translation': 'Supurgi'},
    {'word': 'der Schwamm', 'article': 'der', 'translation': 'Gubka'},
    {'word': 'die Leiter', 'article': 'die', 'translation': 'Narvon'},
    {'word': 'das Seil', 'article': 'das', 'translation': 'Arqon'},
    {'word': 'der Faden', 'article': 'der', 'translation': 'Ip'},
    {'word': 'die Nadel', 'article': 'die', 'translation': 'Igna'},
    {'word': 'das Bügeleisen', 'article': 'das', 'translation': 'Dazmol'},
    {
      'word': 'die Nähmaschine',
      'article': 'die',
      'translation': 'Tikuv mashinasi'
    },
    {'word': 'der Koffer', 'article': 'der', 'translation': 'Jomadon'},
    {'word': 'die Kiste', 'article': 'die', 'translation': 'Yashik'},
    {'word': 'der Karton', 'article': 'der', 'translation': 'Karton quti'},
    {'word': 'die Batterie', 'article': 'die', 'translation': 'Batareya'},
    {'word': 'das Kabel', 'article': 'das', 'translation': 'Kabel'},
    {'word': 'der Stecker', 'article': 'der', 'translation': 'Shtepsel'},
    {'word': 'die Steckdose', 'article': 'die', 'translation': 'Rozetka'},
    {'word': 'der Schalter', 'article': 'der', 'translation': 'Vyklyuchatel'},
    {'word': 'der Bildschirm', 'article': 'der', 'translation': 'Ekran'},
    {'word': 'die Fernbedienung', 'article': 'die', 'translation': 'Pult'},
    {'word': 'der Kopfhörer', 'article': 'der', 'translation': 'Quloqchin'},

    // ===== TABIAT VA HAYVONLAR (QO'SHIMCHA) (30 ta) =====
    {'word': 'der Ozean', 'article': 'der', 'translation': 'Okean'},
    {'word': 'der Dschungel', 'article': 'der', 'translation': 'Jangalzor'},
    {'word': 'die Wüste', 'article': 'die', 'translation': 'Cho\'l'},
    {'word': 'der Vulkan', 'article': 'der', 'translation': 'Vulqon'},
    {'word': 'die Höhle', 'article': 'die', 'translation': 'G\'or'},
    {'word': 'der Wasserfall', 'article': 'der', 'translation': 'Sharshara'},
    {'word': 'der Gletscher', 'article': 'der', 'translation': 'Muzlik'},
    {'word': 'der Planet', 'article': 'der', 'translation': 'Sayyora'},
    {'word': 'das Universum', 'article': 'das', 'translation': 'Koinot'},
    {'word': 'der Komet', 'article': 'der', 'translation': 'Kometa'},
    {'word': 'das Insekt', 'article': 'das', 'translation': 'Hasharot'},
    {'word': 'die Spinne', 'article': 'die', 'translation': 'O\'rgimchak'},
    {'word': 'die Mücke', 'article': 'die', 'translation': 'Chivin'},
    {'word': 'die Fliege', 'article': 'die', 'translation': 'Pashsha'},
    {'word': 'die Ameise', 'article': 'die', 'translation': 'Chumoli'},
    {'word': 'der Käfer', 'article': 'der', 'translation': 'Qo\'ng\'iz'},
    {'word': 'der Wurm', 'article': 'der', 'translation': 'Chuvalchang'},
    {'word': 'die Schnecke', 'article': 'die', 'translation': 'Shilliqqurt'},
    {'word': 'der Schwan', 'article': 'der', 'translation': 'Oqqush'},
    {'word': 'der Pfau', 'article': 'der', 'translation': 'Tovus'},
    {'word': 'die Taube', 'article': 'die', 'translation': 'Kaptar'},
    {'word': 'der Rabe', 'article': 'der', 'translation': 'Qarg\'a'},
    {'word': 'der Papagei', 'article': 'der', 'translation': 'To\'tiqush'},
    {'word': 'das Nashorn', 'article': 'das', 'translation': 'Karkidon'},
    {'word': 'das Flusspferd', 'article': 'das', 'translation': 'Begemot'},
    {'word': 'das Kamel', 'article': 'das', 'translation': 'Tuya'},
    {'word': 'der Hirsch', 'article': 'der', 'translation': 'Bug\'u'},
    {'word': 'das Reh', 'article': 'das', 'translation': 'Ohun'},
    {'word': 'der Biber', 'article': 'der', 'translation': 'Qunduz'},
    {'word': 'der Dachs', 'article': 'der', 'translation': 'Bo\'rsiq'},

    // ===== MEVALAR VA SABZAVOTLAR (QO'SHIMCHA) (30 ta) =====
    {'word': 'die Ananas', 'article': 'die', 'translation': 'Ananas'},
    {'word': 'die Wassermelone', 'article': 'die', 'translation': 'Tarbuz'},
    {'word': 'die Melone', 'article': 'die', 'translation': 'Qovun'},
    {'word': 'der Pfirsich', 'article': 'der', 'translation': 'Shaftoli'},
    {'word': 'die Aprikose', 'article': 'die', 'translation': 'O\'rik'},
    {'word': 'die Pflaume', 'article': 'die', 'translation': 'Olxo\'ri'},
    {'word': 'die Birne', 'article': 'die', 'translation': 'Nok'},
    {'word': 'die Weintraube', 'article': 'die', 'translation': 'Uzum'},
    {'word': 'die Himbeere', 'article': 'die', 'translation': 'Malina'},
    {'word': 'die Brombeere', 'article': 'die', 'translation': 'Maymunjon'},
    {'word': 'die Blaubeere', 'article': 'die', 'translation': 'Chernika'},
    {'word': 'die Kirsche', 'article': 'die', 'translation': 'Gilos'},
    {'word': 'der Granatapfel', 'article': 'der', 'translation': 'Anor'},
    {'word': 'die Feige', 'article': 'die', 'translation': 'Anjir'},
    {'word': 'die Nuss', 'article': 'die', 'translation': 'Yong\'oq'},
    {'word': 'die Mandel', 'article': 'die', 'translation': 'Bodom'},
    {'word': 'der Pilz', 'article': 'der', 'translation': 'Qo\'ziqorin'},
    {'word': 'der Kürbis', 'article': 'der', 'translation': 'Qovoq'},
    {'word': 'die Aubergine', 'article': 'die', 'translation': 'Baqlajon'},
    {
      'word': 'die Paprika',
      'article': 'die',
      'translation': 'Bulg\'or qalampiri'
    },
    {'word': 'der Kohl', 'article': 'der', 'translation': 'Karam'},
    {'word': 'der Brokkoli', 'article': 'der', 'translation': 'Brokkoli'},
    {'word': 'der Blumenkohl', 'article': 'der', 'translation': 'Gulkaram'},
    {'word': 'der Spinat', 'article': 'der', 'translation': 'Ismaloq'},
    {'word': 'die Petersilie', 'article': 'die', 'translation': 'Petrushka'},
    {'word': 'der Dill', 'article': 'der', 'translation': 'Ukrop'},
    {'word': 'die Minze', 'article': 'die', 'translation': 'Yalpiz'},
    {'word': 'der Knoblauch', 'article': 'der', 'translation': 'Sarimsoqpiyoz'},
    {'word': 'der Mais', 'article': 'der', 'translation': 'Makkajo\'xori'},
    {'word': 'die Bohne', 'article': 'die', 'translation': 'Loviya'},

    // ===== OSHXONA BUYUMLARI VA BOSHQA (30 ta) =====
    {'word': 'der Mixer', 'article': 'der', 'translation': 'Mikser'},
    {'word': 'der Toaster', 'article': 'der', 'translation': 'Toster'},
    {
      'word': 'die Mikrowelle',
      'article': 'die',
      'translation': 'Mikroto\'lqinli pech'
    },
    {
      'word': 'der Wasserkocher',
      'article': 'der',
      'translation': 'Choynak (elektr)'
    },
    {
      'word': 'die Teekanne',
      'article': 'die',
      'translation': 'Choynak (damlash uchun)'
    },
    {'word': 'das Brett', 'article': 'das', 'translation': 'Taxtakach'},
    {'word': 'der Deckel', 'article': 'der', 'translation': 'Qopqoq'},
    {'word': 'das Tablett', 'article': 'das', 'translation': 'Patnis'},
    {'word': 'der Krug', 'article': 'der', 'translation': 'Ko\'za'},
    {'word': 'die Schüssel', 'article': 'die', 'translation': 'Kosa'},
    {'word': 'die Serviette', 'article': 'die', 'translation': 'Salfetka'},
    {'word': 'der Strohhalm', 'article': 'der', 'translation': 'Trubochka'},
    {'word': 'der Müll', 'article': 'der', 'translation': 'Axlat'},
    {'word': 'die Asche', 'article': 'die', 'translation': 'Kul'},
    {'word': 'der Staub', 'article': 'der', 'translation': 'Chang'},
    {'word': 'der Fleck', 'article': 'der', 'translation': 'Dog\''},
    {'word': 'der Schwamm', 'article': 'der', 'translation': 'Gubka'},
    {
      'word': 'das Spülmittel',
      'article': 'das',
      'translation': 'Idish yuvish vositasi'
    },
    {
      'word': 'das Waschmittel',
      'article': 'das',
      'translation': 'Kir yuvish kukuni'
    },
    {'word': 'das Shampoo', 'article': 'das', 'translation': 'Shampun'},
    {
      'word': 'die Zahnbürste',
      'article': 'die',
      'translation': 'Tish cho\'tkasi'
    },
    {'word': 'die Zahnpasta', 'article': 'die', 'translation': 'Tish pastasi'},
    {'word': 'der Kamm', 'article': 'der', 'translation': 'Taroq'},
    {'word': 'die Bürste', 'article': 'die', 'translation': 'Cho\'tka'},
    {'word': 'der Rasierer', 'article': 'der', 'translation': 'Ustra'},
    {'word': 'die Creme', 'article': 'die', 'translation': 'Krem'},
    {'word': 'das Parfüm', 'article': 'das', 'translation': 'Atir'},
    {'word': 'das Deo', 'article': 'das', 'translation': 'Dezodorant'},
    {'word': 'das Make-up', 'article': 'das', 'translation': 'Makiyaj'},
    {
      'word': 'der Lippenstift',
      'article': 'der',
      'translation': 'Lab bo\'yog\'i'
    },

    // ===== TRANSPORT VA SAYOHAT (QO'SHIMCHA) (10 ta) =====
    {'word': 'das Ticket', 'article': 'das', 'translation': 'Chipta'},
    {
      'word': 'der Passagier',
      'article': 'der',
      'translation': 'Yo\'lovchi (erkak)'
    },
    {
      'word': 'die Passagierin',
      'article': 'die',
      'translation': 'Yo\'lovchi (ayol)'
    },
    {'word': 'das Gepäck', 'article': 'das', 'translation': 'Yuk'},
    {'word': 'das Zelt', 'article': 'das', 'translation': 'Chodir'},
    {'word': 'der Schlafsack', 'article': 'der', 'translation': 'Uxlash qopi'},
    {'word': 'der Kompass', 'article': 'der', 'translation': 'Kompas'},
    {'word': 'die Karte', 'article': 'die', 'translation': 'Xarita'},
    {'word': 'der Zoll', 'article': 'der', 'translation': 'Bojxona'},
    {'word': 'das Souvenir', 'article': 'das', 'translation': 'Suvenir'},

    // ===== UMUMIY (10 ta) =====
    {'word': 'die Wahrheit', 'article': 'die', 'translation': 'Haqiqat'},
    {'word': 'die Lüge', 'article': 'die', 'translation': 'Yolg\'on'},
    {'word': 'das Geheimnis', 'article': 'das', 'translation': 'Sir'},
    {'word': 'der Beweis', 'article': 'der', 'translation': 'Dalil'},
    {'word': 'die Gefahr', 'article': 'die', 'translation': 'Xavf'},
    {'word': 'die Sicherheit', 'article': 'die', 'translation': 'Xavfsizlik'},
    {'word': 'die Freiheit', 'article': 'die', 'translation': 'Erkinlik'},
    {'word': 'die Wahl', 'article': 'die', 'translation': 'Tanlov'},
    {'word': 'der Erfolg', 'article': 'der', 'translation': 'Muvaffaqiyat'},
    {
      'word': 'der Misserfolg',
      'article': 'der',
      'translation': 'Muvaffaqiyatsizlik'
    },
  ];

  static int get totalWords => derDieDasWords.length;

  /// Tanlangan til bo'yicha tarjima (uz / ru / kaa / de).
  static String localizedTranslation(
    Map<String, String> entry, [
    String? localeCode,
  ]) {
    return GameWordsI18n.localized(entry, localeCode ?? LocaleManager.code);
  }

  /// Artiklsiz ot (masalan: `der Mann` → `Mann`)
  static String nounWithoutArticle(Map<String, String> entry) {
    final word = entry['word'] ?? '';
    final article = entry['article'] ?? '';
    final prefix = '$article ';
    if (article.isNotEmpty && word.startsWith(prefix)) {
      return word.substring(prefix.length);
    }
    return word;
  }

  /// Tasodifiy tartiblangan nusxa (asosiy ro'yxatni buzmaydi)
  static List<Map<String, String>> shuffledWords({int? limit, String? level}) {
    List<Map<String, String>> source;
    switch (level) {
      case 'A1':
        source = derDieDasWords.sublist(0, (derDieDasWords.length * 0.37).round()); // ~250 oddiy so'z
        break;
      case 'A2':
        source = derDieDasWords.sublist(0, (derDieDasWords.length * 0.75).round()); // ~500 so'z
        break;
      default:
        source = derDieDasWords; // B1/B2 — barchasi
    }
    final copy = List<Map<String, String>>.from(source);
    copy.shuffle();
    if (limit != null && limit > 0 && limit < copy.length) {
      return copy.sublist(0, limit);
    }
    return copy;
  }

  static Map<String, String> randomWord() {
    return shuffledWords(limit: 1).first;
  }

  static List<Map<String, String>> getWordsByCategory(String category) {
    return derDieDasWords.where((w) => w['category'] == category).toList();
  }
}
